
CREATE TABLE KHACHHANG
(
	MAKH int NOT NULL,
	PASS char(20) NOT NULL,
	EMAIL varchar(30) NOT NULL UNIQUE,
	HOTEN nvarchar(20) NOT NULL,
	SDT char(10) NOT NULL,
	DIACHI nvarchar(50),
	CONSTRAINT PK_KHACHHANG PRIMARY KEY(MAKH)
);

CREATE TABLE THE
(
	SOTHE char(20) NOT NULL,
	CHUTK nvarchar(20),
	NGANHANG nvarchar(50) NOT NULL,
	CONSTRAINT PK_THE PRIMARY KEY(SOTHE)
);

CREATE TABLE DONDATHANG
(
	MADH char(10) NOT NULL,
	NGAYDAT datetime NOT NULL,
	NGAYGIAO datetime NOT NULL, 
	TONGTIENTHUC money NOT NULL, 
	TINHTRANG nvarchar(15) NOT NULL,
	PTTHANHTOAN nvarchar(10) NOT NULL,
	DIACHIGIAO nvarchar(50) NOT NULL, 
	SDTGIAO char(10) NOT NULL,
	MAKH int NOT NULL,
	MANVLAP int,
	MANVGIAO int,
	MACH int NOT NULL,
	THETHANHTOAN char(20)
	CONSTRAINT PK_DONDATHANG PRIMARY KEY(MADH)
);
ALTER TABLE DONDATHANG
ADD	
	CONSTRAINT FK_DONDATHANG_KHACHHANG FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH) ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT FK_DONDATHANG_TT_NHANVIEN FOREIGN KEY(MANVLAP) REFERENCES TT_NHANVIEN(MANV) ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT FK_DONDATHANG_NVGIAOHANG FOREIGN KEY(MANVGIAO) REFERENCES NVGIAOHANG(MANV) ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT FK_DONDATHANG_MACH FOREIGN KEY(MACH) REFERENCES CUAHANG(MACH) ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT FK_DONDATHANG_THE FOREIGN KEY(THETHANHTOAN) REFERENCES THE(SOTHE) ON DELETE NO ACTION ON UPDATE CASCADE

CREATE TABLE CT_DONDATHANG
(
	ID int NOT NULL,
	MADH int NOT NULL,
	MASP int NOT NULL,
	SOLUONG int NOT NULL, 
	DONGIA float NOT NULL,
	CONSTRAINT PK_CT_DONDATHANG PRIMARY KEY(ID)
);
ALTER TABLE CT_DONDATHANG
ADD	
	CONSTRAINT FK_CT_DONDATHANG_DONDATHANG FOREIGN KEY(MADH) REFERENCES DONDATHANG(MADH) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_CT_DONDATHANG_SANPHAM FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP) ON DELETE CASCADE ON UPDATE CASCADE


CREATE TABLE PHIEUTHUHO
(
	MAPHIEUTHU int NOT NULL,
	TENNGUOINOP nvarchar(20) NOT NULL,
	SOTIEN money NOT NULL,
	NGAYNOP datetime NOT NULL,
	SOTIENTHUC money NOT NULL,
	MADONDH int NOT NULL,
	CONSTRAINT PK_CT_PHIEUTHUHO PRIMARY KEY(MAPHIEUTHU)
);
ALTER TABLE PHIEUTHUHO
ADD	
	CONSTRAINT FK_CT_PHIEUTHUHO_DONDATHANG FOREIGN KEY(SOTIEN) REFERENCES DONDATHANG(MADH) ON DELETE CASCADE ON UPDATE CASCADE,

CREATE TRIGGER DonDatHangHopLe ON DONDATHANG AFTER INSERT
AS
BEGIN
	DECLARE @NgayGiao datetime, @NgayDat datetime
	SELECT @NgayDat = NGAYDAT FROM INSERTED
	SELECT @NgayGiao = NGAYGIAO FROM INSERTED
	IF (DATEDIFF(DAY, @NgayDat, @NgayGiao)) < 0
		ROLLBACK TRAN
END
GO

CREATE TRIGGER UpdateTongTien ON CT_DONDATHANG AFTER INSERT
AS
BEGIN
	UPDATE DONDATHANG SET TONGTIENTHUC = (SELECT SUM(SOLUONG * DONGIA) 
	FROM DONDATHANG JOIN INSERTED ON DONDATHANG.MADH = INSERTED.MADH)
END
GO

CREATE TRIGGER TinhTrangTTHopLe ON DONDATHANG AFTER INSERT
AS
BEGIN
	DECLARE @PTThanhToan char(10), @MaNVGiao int = NULL, @SLPTH int = 0
	SELECT @PTThanhToan = PTTHANHTOAN FROM INSERTED
	SELECT @MaNVGiao = MANVGIAO FROM INSERTED

	IF (@PTThanhToan = N'Tiền mặt' OR @PTThanhToan = N'Thẻ')
		UPDATE DONDATHANG SET TINHTRANG = N'Đã thanh toán'
	ELSE
	BEGIN
		IF (@MaNVGiao IS NOT NULL)
		BEGIN
			SET @SLPTH = (SELECT COUNT(*) FROM PHIEUTHUHO JOIN INSERTED ON PHIEUTHUHO.MADH = INSERTED.MADH)
			IF (@SLPTH = 0)
				UPDATE DONDATHANG SET TINHTRANG = N'Đang giao'
			ELSE
				UPDATE DONDATHANG SET TINHTRANG = N'Đã thanh toán'
		END
		ELSE
			UPDATE DONDATHANG SET TINHTRANG = N'Chưa thanh toán'
	END
END
GO