USE HoaYeuThuong
GO

--CT_DONNHAP
CREATE INDEX IDX_CTDONNHAP ON CT_DONNHAP(MADNH)
--SANPHAM
CREATE INDEX IDX_SANPHAM ON SANPHAM(TENSP)
CREATE INDEX IDX_LOAISANPHAM ON SANPHAM(MALOAI)
--SANPHAMCUAHANG
CREATE INDEX IDX_SANPHAMCUAHANG ON SANPHAM_CUAHANG(MACH)
--DONDATHANG
CREATE INDEX IDX_DONDATHANG1 ON DONDATHANG(MANVLAP)
CREATE INDEX IDX_DONDATHANG2 ON DONDATHANG(MANVGIAO)
CREATE INDEX IDX_DONDATHANG3 ON DONDATHANG(NGAYGIAO)
--CT_DONDATHANG
CREATE INDEX IDX_CTDONDATHANG1 ON CT_DONDATHANG(MADH)
CREATE INDEX IDX_CTDONDATHANG2 ON CT_DONDATHANG(MASP)
CREATE INDEX IDX_CTDONDATHANG3 ON CT_DONDATHANG(SOLUONG)
--NHANVIEN
CREATE INDEX IDX_NHANVIEN ON NHANVIEN(LOAINV)
--LUONGTHUONG
CREATE INDEX IDX_LUONGTHUONG ON LUONGTHUONG(LOAINV)
