USE HoaYeuThuongIndex
GO

--CT_DONDATHANG
CREATE INDEX IDX_CTDONDATHANG2 ON CT_DONDATHANG(MASP) include (MADH)
CREATE INDEX IX_CT_DONDAT_SOLUONG ON CT_DONDATHANG(MASP,MADH)
INCLUDE (SOLUONG)
DROP INDEX IDX_CTDONDATHANG2 on CT_DONDATHANG
DROP INDEX IX_CT_DONDAT_SOLUONG on CT_DONDATHANG

--DONDATHANG
CREATE NONCLUSTERED INDEX IX_DONDAT_NGAYDAT ON DONDATHANG( NGAYDAT desc, tongtienthuc)
DROP INDEX IX_DONDAT_NGAYDAT on DONDATHANG


exec DOANHTHU_CH N'Shop hoa tươi số 1',1,2020
exec sp_XemSanPhamBanChay N'Shop hoa tươi số 1',1,2020


exec sp_helpindex 'CUAHANG'
exec sp_helpindex 'CT_DONDATHANG'
exec sp_helpindex 'DONDATHANG'













--CT_DONNHAP
CREATE INDEX IDX_CTDONNHAP ON CT_DONNHAP(MADNH)
--SANPHAM
CREATE INDEX IDX_LOAISANPHAM ON SANPHAM(MALOAI)
--SANPHAMCUAHANG
CREATE INDEX IDX_SANPHAMCUAHANG ON SANPHAM_CUAHANG(MACH)
--DONDATHANG
CREATE INDEX IDX_DONDATHANG1 ON DONDATHANG(MANVLAP)
CREATE INDEX IDX_DONDATHANG2 ON DONDATHANG(MANVGIAO)
CREATE INDEX IDX_DONDATHANG3 ON DONDATHANG(NGAYGIAO)

--NHANVIEN
CREATE INDEX IDX_NHANVIEN ON NHANVIEN(LOAINV)
--LUONGTHUONG
CREATE INDEX IDX_LUONGTHUONG ON LUONGTHUONG(LOAINV)



