USE [HoaYeuThuong_2]
GO
BEGIN TRANSACTION
----Tao function
CREATE PARTITION FUNCTION [NgayDat_Func](datetime) AS RANGE RIGHT FOR VALUES (N'2000-01-01T00:00:00', N'2001-01-01T00:00:00', N'2002-01-01T00:00:00', N'2003-01-01T00:00:00', N'2004-01-01T00:00:00', N'2005-01-01T00:00:00', N'2006-01-01T00:00:00', N'2007-01-01T00:00:00', N'2008-01-01T00:00:00', N'2009-01-01T00:00:00', N'2010-01-01T00:00:00', N'2011-01-01T00:00:00', N'2012-01-01T00:00:00', N'2013-01-01T00:00:00', N'2014-01-01T00:00:00', N'2015-01-01T00:00:00', N'2016-01-01T00:00:00', N'2017-01-01T00:00:00', N'2018-01-01T00:00:00', N'2019-01-01T00:00:00', N'2020-01-01T00:00:00', N'2021-01-01T00:00:00', N'2022-01-01T00:00:00', N'2023-01-01T00:00:00', N'2024-01-01T00:00:00')

---Tao schema luu file chia 
CREATE PARTITION SCHEME [DonHang_NgayDat_Sc] AS PARTITION [NgayDat_Func] TO ([PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY])


ALTER TABLE [dbo].[CT_DONDATHANG] DROP CONSTRAINT [FK_CT_DONDATHANG_DONDATHANG]


ALTER TABLE [dbo].[PHIEUTHUHO] DROP CONSTRAINT [FK_PHIEUTHUHO_DONDATHANG]



--Drop khoa chinh dondathang truoc


ALTER TABLE [dbo].[DONDATHANG] DROP CONSTRAINT [PK__DONDATHA__603F0047719C51B4] WITH ( ONLINE = OFF )
--them nonclustered cho khoa chinh

ALTER TABLE [dbo].[DONDATHANG] ADD PRIMARY KEY NONCLUSTERED 
(
	[MADH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]


-------------Giai thich: Cai Clustered Index cho NgayDat

CREATE CLUSTERED INDEX [ClusteredIndex_on_DonHang_NgayDat_Sc_637775050038003936] ON [dbo].[DONDATHANG]
(
	[NGAYDAT]
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [DonHang_NgayDat_Sc]([NGAYDAT])

-------Sau do drop luon
DROP INDEX [ClusteredIndex_on_DonHang_NgayDat_Sc_637775050038003936] ON [dbo].[DONDATHANG]



----Them lai cac khoa ngoai
ALTER TABLE [dbo].[CT_DONDATHANG]  WITH CHECK ADD  CONSTRAINT [FK_CT_DONDATHANG_DONDATHANG] FOREIGN KEY([MADH])
REFERENCES [dbo].[DONDATHANG] ([MADH])
ON UPDATE CASCADE
ON DELETE CASCADE
ALTER TABLE [dbo].[CT_DONDATHANG] CHECK CONSTRAINT [FK_CT_DONDATHANG_DONDATHANG]


ALTER TABLE [dbo].[PHIEUTHUHO]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUTHUHO_DONDATHANG] FOREIGN KEY([MADH])
REFERENCES [dbo].[DONDATHANG] ([MADH])
ALTER TABLE [dbo].[PHIEUTHUHO] CHECK CONSTRAINT [FK_PHIEUTHUHO_DONDATHANG]




----Them lai nonslustered index cho ngaydat trong donhang

CREATE NONCLUSTERED INDEX [IX_DONDAT_NGAYDAT] ON [dbo].[DONDATHANG]
(
	[NGAYDAT] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [DonHang_NgayDat_Sc]([NGAYDAT])




CREATE NONCLUSTERED INDEX [IX_DONDAT_TONGTIEN] ON [dbo].[DONDATHANG]
(
	[TONGTIENTHUC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [DonHang_NgayDat_Sc]([NGAYDAT])






COMMIT TRANSACTION
--sau khi ket thuc, nonclustered index của khoa chinh duoc tu dong chuyen ve clustered index vi da cai  PRIMARY KEY NONCLUSTERED 
-- Kiem tra index 
--SELECT so.name as TableName
--      ,si.name as IndexName
--	  ,si.type_desc as IndexType
--	FROM SYS.indexes si join sys.objects so on si.[object_id]=so.[object_id]
--	where so.type='U' and si.name is not null
--	order by so.name,si.type
--Kiem tra lai phan vung
-----PARTITION---
--CHECK PARTITION----
SELECT * FROM SYS.partition_range_values
SELECT * FROM SYS.dm_db_partition_stats WHERE object_id('DONDATHANG')=object_id

